### PR TITLE
rcongui: Fix stats page horizontal scroll

### PR DESCRIPTION
**Pull request by MartijnHols**
The stats page had a horizontal scrollbar. Reorganizing the grids for a bit solves this.

### CODE REVIEW

**Comment by MartijnHols** [comment]
Needs more work

**Comment by MartijnHols** [comment]
Actually it was fine all along. I had some non-committed local changes that ironically introduced the same issue again

**Comment by cemathey** [comment]
Has some merge conflicts now, could you resolve those please.

**Comment by MartijnHols** [comment]
It's ready now

**Comment by MartijnHols** [comment]
It's really ready now

**Comment by cemathey** [comment]
I built it and connected it to our live server, looks fine to me.

**Review by cemathey — APPROVED** [review]

**Pull request merged**
