### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ElGuillermo**
strikethrough RCONWEB_SERVER_URL part, as a lot of users don't get that right

### CODE REVIEW

**Comment by caranci** [comment]
I'm not sure that strikethrough is what is needed here. I think most people interpret a strikethrough to mean the text has been deleted or removed and that that they should disregard the text.

**Comment by ElGuillermo** [comment]
Yep. That's it : this parameter has disappeared, replaced by another one in UI config.
This doc has to be rewritten almost entirely :/

**Comment by caranci** [comment]
Ack. I was thinking in terms that the server_url needs to be set... I somehow didn't clue-in to the fact it was the `.env` version of the setting.

**Comment by cemathey** [comment]
I think we should just rewrite the install steps from scratch, if nobody beats me to it I'll spend some time doing it tomorrow.

**Pull request closed without merging**
